service: linebot-s3
provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 512
  timeout: 60
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "*"

functions:
  hello:
    handler: handler.hello
    environment:
      CHANNEL_ID: ''
      CHANNEL_SECRET: ''
      CHANNEL_TOKEN: ''

    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-run-function-plugin
